import * as Astronomy from 'astronomy-engine';

export const SIGNS = ['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'] as const;
export const NAKSHATRAS = ['Ashwini','Bharani','Krittika','Rohini','Mrigashira','Ardra','Punarvasu','Pushya','Ashlesha','Magha','Purva Phalguni','Uttara Phalguni','Hasta','Chitra','Swati','Vishakha','Anuradha','Jyeshtha','Mula','Purva Ashadha','Uttara Ashadha','Shravana','Dhanishta','Shatabhisha','Purva Bhadrapada','Uttara Bhadrapada','Revati'] as const;
const LORDS = ['Ketu','Venus','Sun','Moon','Mars','Rahu','Jupiter','Saturn','Mercury'] as const;
const YEARS: Record<string, number> = {Ketu:7,Venus:20,Sun:6,Moon:10,Mars:7,Rahu:18,Jupiter:16,Saturn:19,Mercury:17};
export type Graha = 'Sun'|'Moon'|'Mars'|'Mercury'|'Jupiter'|'Venus'|'Saturn'|'Rahu'|'Ketu';
export interface BirthInput { name?:string; date:string; time:string; utcOffsetMinutes:number; latitude:number; longitude:number }
export interface GrahaState { name:Graha; longitude:number; sign:string; degree:number; nakshatra:string; pada:number; retrograde:boolean; house:number }
export interface ChartResult { name:string; moment:string; ayanamsa:number; ascendant:{longitude:number;sign:string;degree:number}; midheaven:{longitude:number;sign:string}; planets:GrahaState[]; dasha:{lord:string;balanceYears:number;periodYears:number} }
export interface Place { name:string; country:string; latitude:number; longitude:number; utcOffsetMinutes:number }
export const PLACES:Place[] = [
 {name:'Pune',country:'India',latitude:18.5204,longitude:73.8567,utcOffsetMinutes:330},{name:'Mumbai',country:'India',latitude:19.076,longitude:72.8777,utcOffsetMinutes:330},{name:'Delhi',country:'India',latitude:28.6139,longitude:77.209,utcOffsetMinutes:330},{name:'Bengaluru',country:'India',latitude:12.9716,longitude:77.5946,utcOffsetMinutes:330},{name:'London',country:'United Kingdom',latitude:51.5072,longitude:-0.1276,utcOffsetMinutes:0},{name:'New York',country:'United States',latitude:40.7128,longitude:-74.006,utcOffsetMinutes:-300},{name:'Singapore',country:'Singapore',latitude:1.3521,longitude:103.8198,utcOffsetMinutes:480},{name:'Sydney',country:'Australia',latitude:-33.8688,longitude:151.2093,utcOffsetMinutes:600}
];
const wrap=(n:number)=>((n%360)+360)%360;
const ayanamsa=(date:Date)=>{const t=(date.getTime()-Date.UTC(2000,0,1,12))/86400000/36525;return 23.853336+50.288/3600*t+0.000222*t*t;};
function tropical(body:Astronomy.Body,date:Date){return wrap(Astronomy.Ecliptic(Astronomy.GeoVector(body,date,true)).elon)}
function coordinates(lon:number){const sign=Math.floor(wrap(lon)/30);return {sign:SIGNS[sign]!,degree:wrap(lon)%30,nakshatra:NAKSHATRAS[Math.floor(wrap(lon)/(40/3))]!,pada:Math.floor((wrap(lon)%(40/3))/(10/3))+1}}
function localDate(input:BirthInput){if(!/^\d{4}-\d{2}-\d{2}$/.test(input.date)||!/^\d{2}:\d{2}$/.test(input.time))throw new Error('Enter a valid date and 24-hour time.');if(!Number.isFinite(input.utcOffsetMinutes)||Math.abs(input.utcOffsetMinutes)>840)throw new Error('UTC offset must be between −14 and +14 hours.');if(Math.abs(input.latitude)>90||Math.abs(input.longitude)>180)throw new Error('Location coordinates are out of range.');const [y,m,d]=input.date.split('-').map(Number);const [h,min]=input.time.split(':').map(Number);const date=new Date(Date.UTC(y!,m!-1,d!,h!,min!)-input.utcOffsetMinutes*60000);if(Number.isNaN(date.getTime()))throw new Error('Birth date and time could not be read.');return date;}
function ascendant(date:Date,latitude:number,longitude:number){const jd=date.getTime()/86400000+2440587.5,T=(jd-2451545)/36525;const gmst=wrap(280.46061837+360.98564736629*(jd-2451545)+.000387933*T*T-T*T*T/38710000);const theta=wrap(gmst+longitude)*Math.PI/180,phi=latitude*Math.PI/180,eps=(23.439291-.0130042*T)*Math.PI/180;let asc=wrap(Math.atan2(-Math.cos(theta),Math.sin(theta)*Math.cos(eps)+Math.tan(phi)*Math.sin(eps))*180/Math.PI);const mc=wrap(Math.atan2(Math.sin(theta),Math.cos(theta)*Math.cos(eps))*180/Math.PI);if(wrap(asc-mc)>180)asc=wrap(asc+180);return {asc,mc};}
type ClassicalGraha=Exclude<Graha,'Rahu'|'Ketu'>;
const BODIES:Record<ClassicalGraha,Astronomy.Body>={Sun:Astronomy.Body.Sun,Moon:Astronomy.Body.Moon,Mars:Astronomy.Body.Mars,Mercury:Astronomy.Body.Mercury,Jupiter:Astronomy.Body.Jupiter,Venus:Astronomy.Body.Venus,Saturn:Astronomy.Body.Saturn};
function speed(body:Astronomy.Body,date:Date){const before=new Date(date.getTime()-3600000),after=new Date(date.getTime()+3600000);let delta=wrap(tropical(body,after)-tropical(body,before));if(delta>180)delta-=360;return delta;}
function vimshottari(moonLongitude:number){const span=40/3,index=Math.floor(wrap(moonLongitude)/span),within=wrap(moonLongitude)%span,lord=LORDS[index%9]!,years=YEARS[lord]!,balanceYears=years*(1-within/span);return {lord,balanceYears,periodYears:years};}
export function calculateChart(input:BirthInput):ChartResult{const date=localDate(input),ayan=ayanamsa(date),{asc,mc}=ascendant(date,input.latitude,input.longitude),siderealAsc=wrap(asc-ayan),ascSign=Math.floor(siderealAsc/30);const planets:GrahaState[]=[];for(const name of Object.keys(BODIES) as ClassicalGraha[]){const body=BODIES[name]!,longitude=wrap(tropical(body,date)-ayan),c=coordinates(longitude),retrograde=speed(body,date)<0;planets.push({name,longitude,...c,retrograde,house:(Math.floor(longitude/30)-ascSign+12)%12+1});}const moon=planets.find(p=>p.name==='Moon')!;const northNode=wrap(125.04452-1934.136261*((date.getTime()/86400000+2440587.5-2451545)/36525));for(const [name,longitude] of [['Rahu',wrap(northNode-ayan)],['Ketu',wrap(northNode+180-ayan)]] as const){const c=coordinates(longitude);planets.push({name,longitude,...c,retrograde:true,house:(Math.floor(longitude/30)-ascSign+12)%12+1});}return {name:input.name?.trim()||'Birth chart',moment:date.toISOString(),ayanamsa:ayan,ascendant:{longitude:siderealAsc,sign:SIGNS[ascSign]!,degree:siderealAsc%30},midheaven:{longitude:wrap(mc-ayan),sign:SIGNS[Math.floor(wrap(mc-ayan)/30)]!},planets,dasha:vimshottari(moon.longitude)};}
export function calculatePanchang(date:string,utcOffsetMinutes=330){const noon=new Date(`${date}T12:00:00Z`);if(Number.isNaN(noon.getTime()))throw new Error('Enter a valid calendar date.');const utc=new Date(noon.getTime()-utcOffsetMinutes*60000),sun=wrap(tropical(Astronomy.Body.Sun,utc)-ayanamsa(utc)),moon=wrap(tropical(Astronomy.Body.Moon,utc)-ayanamsa(utc)),tithi=Math.floor(wrap(moon-sun)/12)+1,yoga=Math.floor(wrap(sun+moon)/(40/3))+1,nak=Math.floor(moon/(40/3));return {date,ayanamsa:ayanamsa(utc),tithi:{number:tithi,half:tithi===15?'Purnima':tithi===30?'Amavasya':tithi<=15?'Shukla':'Krishna'},nakshatra:NAKSHATRAS[nak]!,yoga:yoga,nakshatraLord:LORDS[nak%9]!,sunrise:null as string|null,note:'Solar events require a precise elevation and horizon model; sunrise and sunset are not included in this preview.'};}
export function scoreMatch(a:ChartResult,b:ChartResult){const moonA=a.planets.find(p=>p.name==='Moon')!,moonB=b.planets.find(p=>p.name==='Moon')!;const taraDistance=(Math.floor(moonB.longitude/(40/3))-Math.floor(moonA.longitude/(40/3))+27)%27+1;const taraScore=[2,4,6,8,9].includes((taraDistance-1)%9+1)?1.5:0;const rashiDistance=(Math.floor(moonB.longitude/30)-Math.floor(moonA.longitude/30)+12)%12+1;const bhakoot=[2,5,6,8,9,12].includes(rashiDistance)?0:7;const kootas=[{name:'Tara',score:taraScore,max:3},{name:'Bhakoot',score:bhakoot,max:7}];return {score:kootas.reduce((n,k)=>n+k.score,0),max:36,kootas,complete:false,notice:'This preview calculates Tara and Bhakoot only. The remaining six kootas and cancellation rules are not yet assessed; do not use this score as a complete Ashtakoota result.'};}
export { SIGNS as signs, NAKSHATRAS as nakshatras };
